site_name: Lukaa's Page 

theme:
  name: material
  features:
    # Set the navigation
    - navigation.tabs
    # Set he navigation unmoved
    - navigation.tabs.sticky
    # Show the navigation path
    - navigation.path
    # Set the view follow
    - toc.follow
    # Return to the top button
    - navigation.top

  # Set the logo
  logo: logo.jpg
  favicon: logo.jpg

  # Set the icons
  icon:
    # Last and next page icon
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right

  # Set the font
  font:
    text: Merriweather
  # Set the setting about the white/dark mode
  palette: 

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)" # make the initial color is the same as the system setting
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav:
  - 主页: 'index.md'
  #- 学校课程:
  - Self-Learning: 
    - 搭建Blog: 'blogBuilding/build.md'
    - TryNext: 'index.md'

  #- 其他:

# Set the website when click the logo
extra:
  homepage: https://lukaa0724.github.io/blog/ 


extra_javascript:
  - javascripts/extra.js
extra_css:
  - stylesheets/extra.css